# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

uiLevenshteinDistance <- function(s1, s2) {
    .Call('authGraph_uiLevenshteinDistance', PACKAGE = 'authGraph', s1, s2)
}

levVectors <- function(x, y) {
    .Call('authGraph_levVectors', PACKAGE = 'authGraph', x, y)
}

